spring.application.name=springboot-rabbitmq-project

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

rabbitmq.queue.name=projectQueue
rabbitmq.exchange.name=projectExchange
rabbitmq.routingKey.name=project_routing_key

rabbitmq.queue.json.name=projectQueue_json
rabbitmq.routingKey.json.name=project_routing_key_json