spring.application.name=springboot-rabbitmq-project

spring.rabbimq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.passsword=guest

rabbitmq.queue.name=projectQueue
rabbitmq.exchange.name=projectExchange
rabbitmq.routingKey.name=project_routing_key